server:
  port: 8899

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.201.91:13306/oauth2
    username: root
    password: root
    tomcat:
      initial-size: 1
      max-idle: 20
      min-idle: 1
      max-active: 20
      max-wait: 6000
  
#mybatis
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.wbda.oauth2.entity

#
app:
  security:
    passwordStrength: 10
    tokenSigningKey: wbda123